/*
 * generated by Xtext 2.32.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.initconfig.ui.internal.InitconfigActivator;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class InitConfigExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(InitconfigActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		InitconfigActivator activator = InitconfigActivator.getInstance();
		return activator != null ? activator.getInjector(InitconfigActivator.ORG_XTEXT_INITCONFIG) : null;
	}

}
