/*
 * generated by Xtext 2.32.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.jenkins.ui.internal.JenkinsActivator;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JenkinsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(JenkinsActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		JenkinsActivator activator = JenkinsActivator.getInstance();
		return activator != null ? activator.getInjector(JenkinsActivator.ORG_XTEXT_JENKINS) : null;
	}

}
