/*
 * generated by Xtext 2.32.0
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class InitConfigUiModule extends AbstractInitConfigUiModule {

	public InitConfigUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
