/*
 * generated by Xtext 2.32.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.JenkinsRuntimeModule;
import org.xtext.JenkinsStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class JenkinsIdeSetup extends JenkinsStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new JenkinsRuntimeModule(), new JenkinsIdeModule()));
	}
	
}
