/*
 * generated by Xtext 2.32.0
 */
package org.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.parser.antlr.internal.InternalInitConfigParser;
import org.xtext.services.InitConfigGrammarAccess;

public class InitConfigParser extends AbstractAntlrParser {

	@Inject
	private InitConfigGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalInitConfigParser createParser(XtextTokenStream stream) {
		return new InternalInitConfigParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Projet";
	}

	public InitConfigGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(InitConfigGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
