/*
 * generated by Xtext 2.32.0
 */
package org.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class InitConfigGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ProjetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.InitConfig.Projet");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProjetKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cUrlKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cUrlAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cUrlEStringParserRuleCall_3_1_0 = (RuleCall)cUrlAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cBranchKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cBranchAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cBranchEStringParserRuleCall_4_1_0 = (RuleCall)cBranchAssignment_4_1.eContents().get(0);
		private final Keyword cDependancesprojetKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cDependancesprojetAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cDependancesprojetDependancesProjetParserRuleCall_7_0 = (RuleCall)cDependancesprojetAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cDependancesprojetAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cDependancesprojetDependancesProjetParserRuleCall_8_1_0 = (RuleCall)cDependancesprojetAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cConfigurationKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cConfigurationAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cConfigurationTestingParserRuleCall_11_0 = (RuleCall)cConfigurationAssignment_11.eContents().get(0);
		private final Group cGroup_12 = (Group)cGroup.eContents().get(12);
		private final Keyword cEtapesperslKeyword_12_0 = (Keyword)cGroup_12.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_12_1 = (Keyword)cGroup_12.eContents().get(1);
		private final Assignment cEtapesperslAssignment_12_2 = (Assignment)cGroup_12.eContents().get(2);
		private final RuleCall cEtapesperslEtapesperslParserRuleCall_12_2_0 = (RuleCall)cEtapesperslAssignment_12_2.eContents().get(0);
		private final Group cGroup_12_3 = (Group)cGroup_12.eContents().get(3);
		private final Keyword cCommaKeyword_12_3_0 = (Keyword)cGroup_12_3.eContents().get(0);
		private final Assignment cEtapesperslAssignment_12_3_1 = (Assignment)cGroup_12_3.eContents().get(1);
		private final RuleCall cEtapesperslEtapesperslParserRuleCall_12_3_1_0 = (RuleCall)cEtapesperslAssignment_12_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12_4 = (Keyword)cGroup_12.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Projet returns Projet:
		//    'Projet'
		//    name=EString
		//    '{'
		//        ('url' url=EString)?
		//        ('branch' branch=EString)?
		//        'dependancesprojet' '{' dependancesprojet+=DependancesProjet ( "," dependancesprojet+=DependancesProjet)* '}'
		//        'configuration' configuration=Testing
		//        ('etapespersl' '{' etapespersl+=Etapespersl ( "," etapespersl+=Etapespersl)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Projet'
		//name=EString
		//'{'
		//    ('url' url=EString)?
		//    ('branch' branch=EString)?
		//    'dependancesprojet' '{' dependancesprojet+=DependancesProjet ( "," dependancesprojet+=DependancesProjet)* '}'
		//    'configuration' configuration=Testing
		//    ('etapespersl' '{' etapespersl+=Etapespersl ( "," etapespersl+=Etapespersl)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Projet'
		public Keyword getProjetKeyword_0() { return cProjetKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('url' url=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'url'
		public Keyword getUrlKeyword_3_0() { return cUrlKeyword_3_0; }
		
		//url=EString
		public Assignment getUrlAssignment_3_1() { return cUrlAssignment_3_1; }
		
		//EString
		public RuleCall getUrlEStringParserRuleCall_3_1_0() { return cUrlEStringParserRuleCall_3_1_0; }
		
		//('branch' branch=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'branch'
		public Keyword getBranchKeyword_4_0() { return cBranchKeyword_4_0; }
		
		//branch=EString
		public Assignment getBranchAssignment_4_1() { return cBranchAssignment_4_1; }
		
		//EString
		public RuleCall getBranchEStringParserRuleCall_4_1_0() { return cBranchEStringParserRuleCall_4_1_0; }
		
		//'dependancesprojet'
		public Keyword getDependancesprojetKeyword_5() { return cDependancesprojetKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//dependancesprojet+=DependancesProjet
		public Assignment getDependancesprojetAssignment_7() { return cDependancesprojetAssignment_7; }
		
		//DependancesProjet
		public RuleCall getDependancesprojetDependancesProjetParserRuleCall_7_0() { return cDependancesprojetDependancesProjetParserRuleCall_7_0; }
		
		//( "," dependancesprojet+=DependancesProjet)*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//dependancesprojet+=DependancesProjet
		public Assignment getDependancesprojetAssignment_8_1() { return cDependancesprojetAssignment_8_1; }
		
		//DependancesProjet
		public RuleCall getDependancesprojetDependancesProjetParserRuleCall_8_1_0() { return cDependancesprojetDependancesProjetParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//'configuration'
		public Keyword getConfigurationKeyword_10() { return cConfigurationKeyword_10; }
		
		//configuration=Testing
		public Assignment getConfigurationAssignment_11() { return cConfigurationAssignment_11; }
		
		//Testing
		public RuleCall getConfigurationTestingParserRuleCall_11_0() { return cConfigurationTestingParserRuleCall_11_0; }
		
		//('etapespersl' '{' etapespersl+=Etapespersl ( "," etapespersl+=Etapespersl)* '}' )?
		public Group getGroup_12() { return cGroup_12; }
		
		//'etapespersl'
		public Keyword getEtapesperslKeyword_12_0() { return cEtapesperslKeyword_12_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_12_1() { return cLeftCurlyBracketKeyword_12_1; }
		
		//etapespersl+=Etapespersl
		public Assignment getEtapesperslAssignment_12_2() { return cEtapesperslAssignment_12_2; }
		
		//Etapespersl
		public RuleCall getEtapesperslEtapesperslParserRuleCall_12_2_0() { return cEtapesperslEtapesperslParserRuleCall_12_2_0; }
		
		//( "," etapespersl+=Etapespersl)*
		public Group getGroup_12_3() { return cGroup_12_3; }
		
		//","
		public Keyword getCommaKeyword_12_3_0() { return cCommaKeyword_12_3_0; }
		
		//etapespersl+=Etapespersl
		public Assignment getEtapesperslAssignment_12_3_1() { return cEtapesperslAssignment_12_3_1; }
		
		//Etapespersl
		public RuleCall getEtapesperslEtapesperslParserRuleCall_12_3_1_0() { return cEtapesperslEtapesperslParserRuleCall_12_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_12_4() { return cRightCurlyBracketKeyword_12_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.InitConfig.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class DependancesProjetElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.InitConfig.DependancesProjet");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDependancesProjetAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDependancesProjetKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cNomKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cNomAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNomEStringParserRuleCall_3_1_0 = (RuleCall)cNomAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVersionKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cVersionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cVersionEStringParserRuleCall_4_1_0 = (RuleCall)cVersionAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cConfigurationKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cConfigurationAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cConfigurationEStringParserRuleCall_5_1_0 = (RuleCall)cConfigurationAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//DependancesProjet returns DependancesProjet:
		//    {DependancesProjet}
		//    'DependancesProjet'
		//    '{'
		//        ('nom' nom=EString)?
		//        ('version' version=EString)?
		//        ('configuration' configuration=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{DependancesProjet}
		//'DependancesProjet'
		//'{'
		//    ('nom' nom=EString)?
		//    ('version' version=EString)?
		//    ('configuration' configuration=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{DependancesProjet}
		public Action getDependancesProjetAction_0() { return cDependancesProjetAction_0; }
		
		//'DependancesProjet'
		public Keyword getDependancesProjetKeyword_1() { return cDependancesProjetKeyword_1; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('nom' nom=EString)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'nom'
		public Keyword getNomKeyword_3_0() { return cNomKeyword_3_0; }
		
		//nom=EString
		public Assignment getNomAssignment_3_1() { return cNomAssignment_3_1; }
		
		//EString
		public RuleCall getNomEStringParserRuleCall_3_1_0() { return cNomEStringParserRuleCall_3_1_0; }
		
		//('version' version=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'version'
		public Keyword getVersionKeyword_4_0() { return cVersionKeyword_4_0; }
		
		//version=EString
		public Assignment getVersionAssignment_4_1() { return cVersionAssignment_4_1; }
		
		//EString
		public RuleCall getVersionEStringParserRuleCall_4_1_0() { return cVersionEStringParserRuleCall_4_1_0; }
		
		//('configuration' configuration=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'configuration'
		public Keyword getConfigurationKeyword_5_0() { return cConfigurationKeyword_5_0; }
		
		//configuration=EString
		public Assignment getConfigurationAssignment_5_1() { return cConfigurationAssignment_5_1; }
		
		//EString
		public RuleCall getConfigurationEStringParserRuleCall_5_1_0() { return cConfigurationEStringParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class TestingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.InitConfig.Testing");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cTestingAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTestingKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTargetKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTargetAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTargetEStringParserRuleCall_4_1_0 = (RuleCall)cTargetAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCmdtestKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cCmdtestAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cCmdtestEStringParserRuleCall_5_1_0 = (RuleCall)cCmdtestAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Testing returns Testing:
		//    {Testing}
		//    'Testing'
		//    name=EString
		//    '{'
		//        ('target' target=EString)?
		//        ('cmdtest' cmdtest=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Testing}
		//'Testing'
		//name=EString
		//'{'
		//    ('target' target=EString)?
		//    ('cmdtest' cmdtest=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Testing}
		public Action getTestingAction_0() { return cTestingAction_0; }
		
		//'Testing'
		public Keyword getTestingKeyword_1() { return cTestingKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('target' target=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'target'
		public Keyword getTargetKeyword_4_0() { return cTargetKeyword_4_0; }
		
		//target=EString
		public Assignment getTargetAssignment_4_1() { return cTargetAssignment_4_1; }
		
		//EString
		public RuleCall getTargetEStringParserRuleCall_4_1_0() { return cTargetEStringParserRuleCall_4_1_0; }
		
		//('cmdtest' cmdtest=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'cmdtest'
		public Keyword getCmdtestKeyword_5_0() { return cCmdtestKeyword_5_0; }
		
		//cmdtest=EString
		public Assignment getCmdtestAssignment_5_1() { return cCmdtestAssignment_5_1; }
		
		//EString
		public RuleCall getCmdtestEStringParserRuleCall_5_1_0() { return cCmdtestEStringParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EtapesperslElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.InitConfig.Etapespersl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEtapesperslAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEtapesperslKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCmdKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cCmdAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cCmdEStringParserRuleCall_4_1_0 = (RuleCall)cCmdAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cDescriptionKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cDescriptionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_5_1_0 = (RuleCall)cDescriptionAssignment_5_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Etapespersl returns Etapespersl:
		//    {Etapespersl}
		//    'Etapespersl'
		//    name=EString
		//    '{'
		//        ('cmd' cmd=EString)?
		//        ('description' description=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Etapespersl}
		//'Etapespersl'
		//name=EString
		//'{'
		//    ('cmd' cmd=EString)?
		//    ('description' description=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Etapespersl}
		public Action getEtapesperslAction_0() { return cEtapesperslAction_0; }
		
		//'Etapespersl'
		public Keyword getEtapesperslKeyword_1() { return cEtapesperslKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('cmd' cmd=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'cmd'
		public Keyword getCmdKeyword_4_0() { return cCmdKeyword_4_0; }
		
		//cmd=EString
		public Assignment getCmdAssignment_4_1() { return cCmdAssignment_4_1; }
		
		//EString
		public RuleCall getCmdEStringParserRuleCall_4_1_0() { return cCmdEStringParserRuleCall_4_1_0; }
		
		//('description' description=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'description'
		public Keyword getDescriptionKeyword_5_0() { return cDescriptionKeyword_5_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_5_1() { return cDescriptionAssignment_5_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_5_1_0() { return cDescriptionEStringParserRuleCall_5_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	
	
	private final ProjetElements pProjet;
	private final EStringElements pEString;
	private final DependancesProjetElements pDependancesProjet;
	private final TestingElements pTesting;
	private final EtapesperslElements pEtapespersl;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public InitConfigGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProjet = new ProjetElements();
		this.pEString = new EStringElements();
		this.pDependancesProjet = new DependancesProjetElements();
		this.pTesting = new TestingElements();
		this.pEtapespersl = new EtapesperslElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.InitConfig".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Projet returns Projet:
	//    'Projet'
	//    name=EString
	//    '{'
	//        ('url' url=EString)?
	//        ('branch' branch=EString)?
	//        'dependancesprojet' '{' dependancesprojet+=DependancesProjet ( "," dependancesprojet+=DependancesProjet)* '}'
	//        'configuration' configuration=Testing
	//        ('etapespersl' '{' etapespersl+=Etapespersl ( "," etapespersl+=Etapespersl)* '}' )?
	//    '}';
	public ProjetElements getProjetAccess() {
		return pProjet;
	}
	
	public ParserRule getProjetRule() {
		return getProjetAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//DependancesProjet returns DependancesProjet:
	//    {DependancesProjet}
	//    'DependancesProjet'
	//    '{'
	//        ('nom' nom=EString)?
	//        ('version' version=EString)?
	//        ('configuration' configuration=EString)?
	//    '}';
	public DependancesProjetElements getDependancesProjetAccess() {
		return pDependancesProjet;
	}
	
	public ParserRule getDependancesProjetRule() {
		return getDependancesProjetAccess().getRule();
	}
	
	//Testing returns Testing:
	//    {Testing}
	//    'Testing'
	//    name=EString
	//    '{'
	//        ('target' target=EString)?
	//        ('cmdtest' cmdtest=EString)?
	//    '}';
	public TestingElements getTestingAccess() {
		return pTesting;
	}
	
	public ParserRule getTestingRule() {
		return getTestingAccess().getRule();
	}
	
	//Etapespersl returns Etapespersl:
	//    {Etapespersl}
	//    'Etapespersl'
	//    name=EString
	//    '{'
	//        ('cmd' cmd=EString)?
	//        ('description' description=EString)?
	//    '}';
	public EtapesperslElements getEtapesperslAccess() {
		return pEtapespersl;
	}
	
	public ParserRule getEtapesperslRule() {
		return getEtapesperslAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
