/*
 * generated by Xtext 2.32.0
 */
package org.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class InitConfigStandaloneSetup extends InitConfigStandaloneSetupGenerated {

	public static void doSetup() {
		new InitConfigStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
