/*
 * generated by Xtext 2.32.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.initconfig.ui.internal.InitconfigActivator;

public class InitConfigUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return InitconfigActivator.getInstance().getInjector("org.xtext.InitConfig");
	}

}
