/*
 * generated by Xtext 2.32.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.jenkins.ui.internal.JenkinsActivator;

public class JenkinsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return JenkinsActivator.getInstance().getInjector("org.xtext.Jenkins");
	}

}
