/*
 * generated by Xtext 2.32.0
 */
package org.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.parser.antlr.internal.InternalJenkinsParser;
import org.xtext.services.JenkinsGrammarAccess;

public class JenkinsParser extends AbstractAntlrParser {

	@Inject
	private JenkinsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalJenkinsParser createParser(XtextTokenStream stream) {
		return new InternalJenkinsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "config";
	}

	public JenkinsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(JenkinsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
