/**
 * generated by Xtext 2.32.0
 */
package org.xtext.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.services.InitConfigGrammarAccess;

@SuppressWarnings("all")
public class InitConfigFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private InitConfigGrammarAccess _initConfigGrammarAccess;

  protected void _format(final /* Projet */Object projet, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\ndependancesprojet cannot be resolved"
      + "\nformat cannot be resolved"
      + "\nconfiguration cannot be resolved"
      + "\nformat cannot be resolved"
      + "\netapespersl cannot be resolved"
      + "\nformat cannot be resolved");
  }

  public void format(final Object projet, final IFormattableDocument document) {
    if (projet instanceof XtextResource) {
      _format((XtextResource)projet, document);
      return;
    } else if (projet instanceof EObject) {
      _format((EObject)projet, document);
      return;
    } else if (projet == null) {
      _format((Void)null, document);
      return;
    } else if (projet != null) {
      _format(projet, document);
      return;
    } else if (projet != null) {
      _format(projet, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(projet, document).toString());
    }
  }
}
